GET https://url-shorter-production-3772.up.railway.app

###
POST https://url-shorter-production-3772.up.railway.app/

Content-Type: application/json
{
    "fullUrl": "https://www.twitch.tv/search?term=midudev"
}